import type { ReactNode } from "react";
import { IconActivity, IconAudioWave, IconBase64, IconCamera, IconCase, IconChevronsLeft, IconChevronsRight, IconClock, IconCloud, IconCron, IconDocText, IconFileCheck,
  IconFileStack, IconFileDiff, IconFileType, IconBadgeCheck, IconFilm, IconFingerprint, IconGithub, IconGlobe, IconHash, IconHome, IconHttp, IconImage, IconInfo, IconJson, IconKey, IconLink, IconMenu, IconMonitor, IconMoon, IconPlus, IconQr, IconRepeat, IconScan, IconSearch, IconSun, IconTextSearch, IconTransfer, IconVideo, IconWifi, IconX } from "./icons";

export const ICONS: Record<string, (p: { width?: number; height?: number }) => ReactNode> = {
  transfer: IconTransfer,
  qr: IconQr,
  base64: IconBase64,
  json: IconJson,
  cron: IconCron,
  convert: IconRepeat,
  ts: IconClock,
  hash: IconHash,
  uuid: IconFingerprint,
  diff: IconFileDiff,
  regex: IconTextSearch,
  text: IconDocText,
  url: IconLink,
  jwt: IconKey,
  "file-hash": IconFileCheck,
  IconFileStack,
  "device-info": IconMonitor,
  case: IconCase,
  mime: IconFileType,
  "http-status": IconActivity,
  pdf: IconFileStack,
  image: IconImage,
  badge: IconBadgeCheck,
  markdown: IconDocText,
  "http-parse": IconHttp,
  "ws-test": IconWifi,
  "vercel-clean": IconCloud,
  "github-release-clean": IconGithub,
  video: IconVideo,
  audio: IconAudioWave,
  "media-info": IconInfo,
  "video-frames": IconFilm,
  "image-batch": IconImage,
  recorder: IconCamera,
  ocr: IconScan,
  "ip-lookup": IconGlobe,
  "dns-lookup": IconGlobe,
};
